spring:
  profiles:
    active: dev
  application:
    name: Strix
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      add-mappings: true
  messages:
    basename: i18n/strix
strix:
  module:
    sms: true
    oss: true
    auth: false
    push: false
    payment: false
  captcha:
    type: blockPuzzle
    cache-type: redis
    aes-status: true
    water-mark: Strix
    interference-options: 1
    req-frequency-limit-enable: true
    req-get-lock-limit: 5
    req-get-lock-seconds: 300
    req-get-minute-limit: 20
  verifier-counter:
    sms:
      limit: 5
      seconds: 300
    email:
      limit: 5
      seconds: 300
  default-locale: zh_CN
