spring:
  profiles:
    active: dev
  application:
    name: Strix
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      add-mappings: true
strix:
  use-oss-aliyun: false
  use-sms-aliyun: false
  use-wechat-auth: false
  use-wechat-push: false
  use-wechat-payment: false
