spring:
  profiles:
    active: dev
  application:
    name: Strix
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      add-mappings: true
strix:
  captcha:
    type: blockPuzzle
    cache-type: redis
    aes-status: true
    water-mark: Strix
    interference-options: 1
    req-frequency-limit-enable: true
    req-get-lock-limit: 5
    req-get-lock-seconds: 300
    req-get-minute-limit: 20
  use-oss-aliyun: false
  use-sms-aliyun: false
  use-wechat-auth: false
  use-wechat-push: false
  use-wechat-payment: false
