name: Deploy with docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true --batch-mode
      - name: Stop Old Docker
        run: docker stop $(docker ps 'StrixApi' -q)
      - name: Remove Old Docker
        run: docker rm $(docker ps 'StrixApi' -q)
      - name: Docker Build
        run: docker build -f ./Dockerfile -t StrixApi .
      - name: Docker Run
        run: docker run -d --name StrixApi -p 9889:9889 StrixApi
      - name: Clean Old Docker Build
        run: docker image prune -a -f
